export const APP_NAME = 'Yeison Molina'
export const APP_DESCRIPTION = 'Yeison Molina - Personal website and portfolio'
export const APP_URL = 'https://yeisonmolina.vercel.app'
export const APP_BRAND = '{ YM }'
export const APP_AUTHOR = '@hackettyam'
export const APP_LOCALE = 'en'
export const APP_VERSION = '1.0.0'
