export const APP_NAME = 'Yeison Molina'
export const APP_DESCRIPTION = 'Yeison Molina - Personal website and portfolio'
export const APP_URL = 'https://yeisonmolina.vercel.app'
export const APP_BRAND = '{ YM }'
export const APP_AUTHOR = '@hackettyam'
export const APP_LOCALE = 'en'
export const APP_VERSION = '1.0.0'
export const LINKEDIN_URL = 'https://www.linkedin.com/in/yeison-molina/'
export const GITHUB_URL = 'https://github.com/yammusic'
export const CURRICULUM_URL = 'https://docs.google.com/document/d/11v3fciPZqi3grcBTWKGko1u-1H1W73vOXTDBS_220wo/edit?usp=sharing'
export const IS_DEV = process.env.NODE_ENV === 'development'
export const IS_PROD = process.env.NODE_ENV === 'production'
